# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20171106_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('handedness', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('some_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('some_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('some_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('some_snapchat', models.CharField(blank=True, max_length=255, null=True)),
                ('game_years_junior', models.CharField(blank=True, help_text='Given in the format YYYY-YYYY, e.g. 1983-1987', max_length=24, null=True)),
                ('game_years_pro_tribe', models.CharField(blank=True, help_text='Given in the format YYYY-YYYY, e.g. 1983-1987', max_length=24, null=True)),
                ('game_years_pro_other', models.CharField(blank=True, help_text='Given in the format YYYY-YYYY, e.g. 1983-1987', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('position', models.CharField(blank=True, choices=[('fwd', 'Forward'), ('def', 'Defense'), ('goal', 'Goalie'), ('player', 'Player')], max_length=10, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.Member')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.School'),
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(related_name='members', through='teams.TeamMembership', to='teams.Team'),
        ),
    ]
