# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20171124_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
