# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20171208_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player_age_end',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='player_age_start',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(blank=True, choices=[('floorball', 'Floorball'), ('futsal', 'Futsal'), ('soccer', 'Soccer')], max_length=12, null=True),
        ),
    ]
