# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20171208_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='age_level',
            field=models.CharField(blank=True, choices=[('adult', '+20-vuotiaat (Aikuiset)'), ('a', '20-17-vuotiaat (A-juniorit)'), ('b', '17-15-vuotiaat (B-juniorit)'), ('c', '15-13-vuotiaat (C-juniorit)'), ('d', '13-11-vuotiaat (D-juniorit)'), ('e', '11-9-vuotiaat (E-juniorit)'), ('f', '9-7-vuotiaat (F-juniorit)'), ('g', '7-5-vuotiaat (G-juniorit)'), ('h', '5-3-vuotiaat (H-juniorit)'), ('i', '3-1 vuotiaat (I-juniorit)')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='path',
            field=models.CharField(blank=True, choices=[('urheilijan', 'Urheilijan polku (3+)'), ('kilpailijan', 'Kilpailijan polku (3-2)'), ('harrastajan', 'Harrastajan polku (1)'), ('salibandy_koulut', 'Salibandy koulut (1, 2 tai 3)'), ('koulujen_iltapaivatoiminta', 'Koulujen iltapäivätoiminta (1 tai 2)'), ('erityisryhmat', 'Erityisryhmät')], max_length=32, null=True),
        ),
    ]
