# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 07:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20171208_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
