# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
