# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
