# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_team_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='position',
            field=models.CharField(blank=True, choices=[('fwd', 'Forward'), ('def', 'Defense'), ('goal', 'Goalie'), ('coach', 'Coach'), ('support', 'Support'), ('player', 'Player')], max_length=10, null=True),
        ),
    ]
