# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20180228_1121'),
        ('teams', '0016_auto_20180313_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sponsor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor1', to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor2', to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor3', to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor4', to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor5', to='sponsors.Sponsor'),
        ),
    ]
