# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20180411_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
