# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20180228_1121'),
        ('teams', '0018_auto_20180413_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_players', to='sponsors.Sponsor'),
        ),
    ]
