# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20180228_1121'),
        ('teams', '0019_member_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sponsor_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor_4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor_5',
        ),
        migrations.AddField(
            model_name='team',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_teams', to='sponsors.Sponsor'),
        ),
    ]
