# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_auto_20180416_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_players', to='sponsors.Sponsor'),
        ),
    ]
