# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_auto_20180416_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age_level',
            field=models.CharField(blank=True, choices=[('adult', '1997 => (Aikuiset)'), ('a', '1998-2000 (A-juniorit)'), ('b', '2001-2002 (B-juniorit)'), ('c', '2003-2004 (C-juniorit)'), ('d', '2005-2006 (D-juniorit)'), ('e', '2007-2008 (E-juniorit)'), ('f', '2009-2010 (F-juniorit)'), ('g', '2011-2012 (G-juniorit)'), ('h', '2013-2017 (H-juniorit)')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='path',
            field=models.CharField(blank=True, choices=[('urheilijan', '3+ (Urheilijan polku)'), ('kilpailijan', '3-2 (Kilpailijan polku)'), ('harrastajan', '2-1 (Harrastajan polku)'), ('Kaupunginosajoukkueet', 'Kaupunginosajoukkueet (F-G-juniorit)'), ('salibandy_koulut', 'Salibandykoulut (H-juniorit)'), ('koulujen_iltapaivatoiminta', 'Koulujen iltapäivätoiminta (6lk-Esikoulu)'), ('erityisryhmat', 'Erityisryhmät')], max_length=32, null=True),
        ),
    ]
