# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_auto_20180419_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
