# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_auto_20180423_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='show_name_in_modal',
            field=models.BooleanField(default=True),
        ),
    ]
