# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20180521_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
