# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_team_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='age_levels',
            field=models.ManyToManyField(related_name='teams', to='teams.AgeLevel'),
        ),


    ]
