# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 12:06
from __future__ import unicode_literals

from django.db import migrations
from teams.models import AGE_LEVEL_TYPES


def create_age_levels(apps, schema_editor):
    AgeLevel = apps.get_model('teams', 'AgeLevel')
    for i, t in enumerate(AGE_LEVEL_TYPES):
        k, v = t
        AgeLevel.objects.create(name=v, order=i)

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_auto_20181001_1455'),
    ]

    operations = [
        migrations.RunPython(create_age_levels, migrations.RunPython.noop),
    ]
