# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 12:06
from __future__ import unicode_literals

from django.db import migrations
from teams.models import AGE_LEVEL_TYPES


def migrate_teams(apps, schema_editor):
    AgeLevel = apps.get_model('teams', 'AgeLevel')
    Team = apps.get_model('teams', 'Team')
    for t in Team.objects.all():
        if t.age_level:
            name = list(filter(lambda x: x[0] == t.age_level, AGE_LEVEL_TYPES))[0][1]
            print('age level', t.id, name)
            al = AgeLevel.objects.get(name=name)
            t.age_levels.add(al)
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_auto_20181001_1506'),
    ]

    operations = [
        migrations.RunPython(migrate_teams, migrations.RunPython.noop)
    ]
