# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_auto_20181001_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age_levels',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.AgeLevel'),
        ),
    ]
