# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180320_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ingress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
