# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.CharField(choices=[('heimo', 'Heimo'), ('miehet-edustus', 'Miehet-edustus')], default='heimo', max_length=20, null=True),
        ),
    ]
