# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-05 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
