image: docker:stable

stages:
  - build
  - release
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  TEST_IMAGE: montel/westend-indians:test-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  RELEASE_IMAGE: montel/westend-indians:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  CACHE_IMAGE: montel/westend-indians:cached

build-image:
  stage: build
  tags:
    - montel
  before_script:
    - docker login -u "$CI_DOCKERHUB_USER" -p "$CI_DOCKERHUB_PASSWORD"
  script:
    - docker pull $CACHE_IMAGE
    - docker build --file ${PWD}/Dockerfile --tag $TEST_IMAGE --cache-from $CACHE_IMAGE --pull .
    - docker push $TEST_IMAGE

release-image:
  stage: release
  tags:
    - montel
  only:
    - develop
    - master
  before_script:
    - docker login -u "$CI_DOCKERHUB_USER" -p "$CI_DOCKERHUB_PASSWORD"
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker tag $TEST_IMAGE $CACHE_IMAGE
    - docker push $RELEASE_IMAGE
    - docker push $CACHE_IMAGE

deploy-stage:
  stage: deploy
  tags:
    - montel
  image: montel/k8s-tool
  variables:
    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    REPLICAS: 1
    NAMESPACE: westend-indians-stage
  script:
    - export TAG
    - export REPLICAS
    - rancher-deploy.sh -n westend-indians-stage -r montel/westend-indians -y apply ./k8s/deployment.yaml
    - rancher-deploy.sh -n westend-indians-stage -r montel/westend-indians -y apply ./k8s/cron_jobs.yaml
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - montel
  image: montel/k8s-tool
  variables:
    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    REPLICAS: 3
    NAMESPACE: westend-indians-production
  script:
    - export TAG
    - export REPLICAS
    - rancher-deploy.sh -n westend-indians-production -r montel/westend-indians -y apply ./k8s/deployment.yaml
    - rancher-deploy.sh -n westend-indians-production -r montel/westend-indians -y apply ./k8s/cron_jobs.yaml
  only:
    - master
