# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 07:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
