# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsitem_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
