# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180212_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
