# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsitem_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
