# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandingsRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('matches', models.SmallIntegerField()),
                ('wins', models.SmallIntegerField()),
                ('wins_contd_period', models.SmallIntegerField()),
                ('losses', models.SmallIntegerField()),
                ('losses_contd_period', models.SmallIntegerField()),
                ('goals_scored', models.SmallIntegerField()),
                ('goals_suffered', models.SmallIntegerField()),
                ('goal_difference', models.SmallIntegerField()),
                ('points', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StandingsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='standingsrow',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.StandingsSet'),
        ),
        migrations.AddField(
            model_name='standingsrow',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.StatsTeam'),
        ),
    ]
