# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20181106_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedgame',
            name='away_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playedgame',
            name='home_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
