# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20181106_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_upcoming_away_team', to='stats.StatsTeam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_upcoming_home_team', to='stats.StatsTeam')),
            ],
        ),
    ]
