# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
