# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indians', '0002_auto_20171103_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
