apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stats-standings
  namespace: ${NAMESPACE}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        spec:
          containers:
          - name: stats-standings
            image: "${IMAGE}"
            command: ["python"]
            args: ["manage.py", "fetch_standings"]
            envFrom:
            - secretRef:
                name: westend-indians-secret
                optional: false
            - configMapRef:
                name: westend-indians-config
                optional: false
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: 10 4,17,22 * * *
  successfulJobsHistoryLimit: 10
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stats-upcoming
  namespace: ${NAMESPACE}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        spec:
          containers:
          - name: stats-upcoming
            image: "${IMAGE}"
            command: ["python"]
            args: ["manage.py", "fetch_upcoming_games"]
            envFrom:
            - secretRef:
                name: westend-indians-secret
                optional: false
            - configMapRef:
                name: westend-indians-config
                optional: false
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: 35 4 * * *
  successfulJobsHistoryLimit: 10
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stats-played
  namespace: ${NAMESPACE}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        spec:
          containers:
          - name: stats-played
            image: "${IMAGE}"
            command: ["python"]
            args: ["manage.py", "fetch_played_games"]
            envFrom:
            - secretRef:
                name: westend-indians-secret
                optional: false
            - configMapRef:
                name: westend-indians-config
                optional: false
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: 30 4 * * *
  successfulJobsHistoryLimit: 10

