# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('level', models.CharField(blank=True, choices=[('top', 'Top level sponsor'), ('second', 'Second level sponsor'), ('third', 'Third level sponsor')], max_length=12, null=True)),
                ('visible_for_team', models.BooleanField(default=True)),
                ('visible_for_tribe', models.BooleanField(default=True)),
                ('visible_for_frontpage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
