# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20171208_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(blank=True, choices=[('top', 'Top level sponsor'), ('second', 'Second level sponsor'), ('third', 'Third level sponsor'), ('bottom', 'Bottom level logo')], max_length=12, null=True),
        ),
    ]
