# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20180228_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='boost',
            field=models.SmallIntegerField(default=0),
        ),
    ]
