---

- include_tasks: install.freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include_tasks: install.debian.yml
  when: (ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu')
