docker_package_prerequisites:
  - name: docker
    state: absent
  - name: docker-common
    state: absent
  # NOTE! Docker docs say this shouldn't be installed, but removing
  #       it will also remove docker if it's already installed.
  #- name: docker-selinux
  #  state: absent
  - name: docker-engine
    state: absent
    # not available on ubuntu
#  - name: device-mapper-persistent-data
#    state: present
  - name: lvm2
    state: present

docker_debian_repo_key_id: 0EBFCD88
docker_debian_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_debian_repo_url: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
docker_debian_package: 'docker-ce'
docker_debian_package_state: installed

docker_redhat_repo_key: https://download.docker.com/linux/centos/gpg
docker_redhat_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
docker_redhat_package: 'docker-ce'
docker_redhat_package_state: installed

docker_install_compose: true
docker_compose_version: '1.17.1'
docker_compose_path: /usr/local/bin/docker-compose
