# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20171109_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_page_cta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
