# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_homepage_home_page_cta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='home_page_cta',
            new_name='shop_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='shop_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tribe_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tribe_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
