# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:57
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_homepage_lift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lift_bgcolor',
            field=colorful.fields.RGBColorField(blank=True),
        ),
    ]
