# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:57
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_homepage_lift_bgcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventspage',
            old_name='description',
            new_name='partners',
        ),
        migrations.AddField(
            model_name='eventspage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
