# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:33
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('content', '0021_auto_20180209_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativeteampage',
            name='lift_bgcolor',
            field=colorful.fields.RGBColorField(blank=True),
        ),
        migrations.AddField(
            model_name='representativeteampage',
            name='pinnalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='representativeteampage',
            name='pinnalla2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='representativeteampage',
            name='pinnalla3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
