# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 08:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20180216_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamspage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
