# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20180430_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='tables',
            field=models.TextField(blank=True),
        ),
    ]
