# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_videopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativeteamplayerspage',
            name='lift_bgcolor',
        ),
        migrations.RemoveField(
            model_name='representativeteamplayerspage',
            name='pinnalla',
        ),
        migrations.RemoveField(
            model_name='representativeteamplayerspage',
            name='pinnalla2',
        ),
        migrations.RemoveField(
            model_name='representativeteamplayerspage',
            name='pinnalla3',
        ),
    ]
