---
# Centos specific parts of docker install

- name: 'Enforce Docker package requirements'
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: '{{ docker_package_prerequisites }}'

- name: 'Add Docker repository GPG key'
  become: yes
  apt_key:
    id: {{ docker_debian_repo_key_id }}
    url: {{ docker_debian_repo_key_url }}
    state: present

- name: 'Add Docker repository'
  become: yes
  apt_repository:
    repo: '{{ docker_debian_repo_url }}'
    state: present

- name: 'Install Docker'
  package:
    name: '{{ docker_ubuntu_package }}'
    state: '{{ docker_ubuntu_package_state }}'
    update_cache: yes

