---

- name: mailto for cron
  cronvar:
    name: MAILTO
    value: "lauri@montel.fi"

- name: update statistics on stg (standings)
  cron:
    name: stats-standings-stg
    job: /usr/local/bin/docker-compose run --rm stg_indians_site python manage.py fetch_standings > /dev/null
    minute: 35
    hour: 04

- name: update statistics on stg (upcoming)
  cron:
    name: stats-upcoming-stg
    job: /usr/local/bin/docker-compose run --rm stg_indians_site python manage.py fetch_upcoming_games > /dev/null
    minute: 32
    hour: 04

- name: update statistics on stg (played)
  cron:
    name: stats-played-stg
    job: /usr/local/bin/docker-compose run --rm stg_indians_site python manage.py fetch_played_games > /dev/null
    minute: 30
    hour: 04


- name: update statistics (standings)
  cron:
    name: stats-standings
    job: /usr/local/bin/docker-compose run --rm indians_site python manage.py fetch_standings > /dev/null
    minute: 41
    hour: "*/6"

- name: update statistics (upcoming)
  cron:
    name: stats-upcoming
    job: /usr/local/bin/docker-compose run --rm indians_site python manage.py fetch_upcoming_games > /dev/null
    minute: 43
    hour: "*/6"

- name: update statistics (played)
  cron:
    name: stats-played
    job: /usr/local/bin/docker-compose run --rm indians_site python manage.py fetch_played_games > /dev/null
    minute: 47
    hour: "*/6"
