---

#hosts:
#  - webserver:
#    ansible_host: "80.69.173.67"


- hosts: all

  vars:
    server_name: westendindians.fi
    upstream_server: http://127.0.0.1:8001

  roles:
    - montel.nginx-front
    - montel.docker

  tasks:
    - name: Create nginx configuration for production
      become: yes
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/conf.d/production.conf
      notify:
        - restart nginx
