# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180117_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
